"""SQLite storage for completed crop analyses."""

import json
import os
import re
import sqlite3
import uuid
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator

from services.database import database_connection
from services.image import DEFAULT_UPLOAD_DIR


LEGACY_RESULTS_DIR = Path(
    os.getenv("NETRA_ANALYSIS_DIR", DEFAULT_UPLOAD_DIR / "results")
)
_IMAGE_ID_PATTERN = re.compile(
    r"^(?P<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\.(?:jpeg|png)$",
    re.IGNORECASE,
)
_legacy_results_migrated = False


class InvalidImageId(ValueError):
    """Raised when an image ID is not one generated by this service."""


def _validate_image_id(image_id: str) -> str:
    match = _IMAGE_ID_PATTERN.fullmatch(image_id)
    if match is None:
        raise InvalidImageId(image_id)
    return f"{match.group('uuid').lower()}.{image_id.rsplit('.', 1)[-1].lower()}"


@contextmanager
def _connection() -> Iterator[sqlite3.Connection]:
    with database_connection() as connection:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS analysis_results (
                image_id TEXT PRIMARY KEY,
                owner_id TEXT,
                filename TEXT NOT NULL,
                created_at TEXT NOT NULL,
                result_json TEXT NOT NULL
            )
            """
        )
        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_analysis_results_owner_created
            ON analysis_results (owner_id, created_at DESC)
            """
        )
        yield connection


def _migrate_legacy_results() -> None:
    """Import older JSON analysis files into SQLite once per API process."""
    global _legacy_results_migrated
    if _legacy_results_migrated:
        return

    legacy_records: list[dict[str, Any]] = []
    if LEGACY_RESULTS_DIR.exists():
        for result_path in LEGACY_RESULTS_DIR.glob("*.json"):
            try:
                result = json.loads(result_path.read_text(encoding="utf-8"))
                if not isinstance(result, dict):
                    continue
                image_id = _validate_image_id(str(result.get("image_id", "")))
            except (OSError, ValueError):
                continue

            result["image_id"] = image_id
            legacy_records.append(result)

    if legacy_records:
        with _connection() as connection:
            connection.executemany(
                """
                INSERT OR IGNORE INTO analysis_results
                    (image_id, owner_id, filename, created_at, result_json)
                VALUES (?, ?, ?, ?, ?)
                """,
                [
                    (
                        result["image_id"],
                        result.get("owner_id") or None,
                        str(result.get("filename", "upload")),
                        str(result.get("created_at", "")),
                        json.dumps(result, ensure_ascii=False),
                    )
                    for result in legacy_records
                ],
            )

    _legacy_results_migrated = True


def save_analysis_result(result: dict[str, Any]) -> None:
    """Persist one result in the shared application database."""
    _migrate_legacy_results()
    image_id = _validate_image_id(str(result["image_id"]))
    result_to_save = {**result, "image_id": image_id}
    with _connection() as connection:
        connection.execute(
            """
            INSERT INTO analysis_results
                (image_id, owner_id, filename, created_at, result_json)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT(image_id) DO UPDATE SET
                owner_id = excluded.owner_id,
                filename = excluded.filename,
                created_at = excluded.created_at,
                result_json = excluded.result_json
            """,
            (
                image_id,
                result_to_save.get("owner_id") or None,
                str(result_to_save.get("filename", "upload")),
                str(result_to_save.get("created_at", "")),
                json.dumps(result_to_save, ensure_ascii=False),
            ),
        )


def get_analysis_result(image_id: str, owner_id: str) -> dict[str, Any]:
    """Load a saved analysis only when it belongs to the requesting account."""
    normalized_id = _validate_image_id(image_id)
    _migrate_legacy_results()
    with _connection() as connection:
        row = connection.execute(
            "SELECT result_json FROM analysis_results WHERE image_id = ? AND owner_id = ?",
            (normalized_id, owner_id),
        ).fetchone()
    if row is None:
        raise FileNotFoundError(image_id)
    return json.loads(row["result_json"])


def list_analysis_results(owner_id: str) -> list[dict[str, Any]]:
    """Return one account's saved analyses, newest first."""
    _migrate_legacy_results()
    with _connection() as connection:
        rows = connection.execute(
            """
            SELECT result_json FROM analysis_results
            WHERE owner_id = ?
            ORDER BY created_at DESC
            """,
            (owner_id,),
        ).fetchall()
    results = [json.loads(row["result_json"]) for row in rows]
    return [result for result in results if result.get("success") is True]


def assign_unowned_analysis_results(owner_id: str) -> None:
    """Assign legacy shared-workspace results to the first created account."""
    _migrate_legacy_results()

    with _connection() as connection:
        rows = connection.execute(
            """
            SELECT image_id, result_json FROM analysis_results
            WHERE owner_id IS NULL OR owner_id = ''
            """
        ).fetchall()
        for row in rows:
            result = json.loads(row["result_json"])
            result["owner_id"] = owner_id
            connection.execute(
                """
                UPDATE analysis_results SET owner_id = ?, result_json = ?
                WHERE image_id = ?
                """,
                (owner_id, json.dumps(result, ensure_ascii=False), row["image_id"]),
            )

    if not LEGACY_RESULTS_DIR.exists():
        return

    for result_path in LEGACY_RESULTS_DIR.glob("*.json"):
        try:
            result = json.loads(result_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        if (
            not isinstance(result, dict)
            or result.get("success") is not True
            or result.get("owner_id")
        ):
            continue
        result["owner_id"] = owner_id
        temporary_path = result_path.with_name(f"{result_path.stem}.{uuid.uuid4().hex}.tmp")
        try:
            temporary_path.write_text(
                json.dumps(result, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
            os.replace(temporary_path, result_path)
        except OSError:
            continue
        finally:
            temporary_path.unlink(missing_ok=True)
