"""Persistent storage for completed crop analyses."""

import json
import os
import re
import uuid
from pathlib import Path
from typing import Any

from services.image import DEFAULT_UPLOAD_DIR


RESULTS_DIR = Path(
    os.getenv("NETRA_ANALYSIS_DIR", DEFAULT_UPLOAD_DIR / "results")
)
_IMAGE_ID_PATTERN = re.compile(
    r"^(?P<uuid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\.(?:jpeg|png)$",
    re.IGNORECASE,
)


class InvalidImageId(ValueError):
    """Raised when an image ID is not one generated by this service."""


def _result_path(image_id: str) -> Path:
    match = _IMAGE_ID_PATTERN.fullmatch(image_id)
    if match is None:
        raise InvalidImageId(image_id)
    return RESULTS_DIR / f"{match.group('uuid').lower()}.json"


def save_analysis_result(result: dict[str, Any]) -> None:
    """Write a result atomically so concurrent readers never see partial JSON."""
    image_id = str(result["image_id"])
    result_path = _result_path(image_id)
    result_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = result_path.with_name(
        f"{result_path.stem}.{uuid.uuid4().hex}.tmp"
    )
    try:
        temporary_path.write_text(
            json.dumps(result, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        os.replace(temporary_path, result_path)
    finally:
        temporary_path.unlink(missing_ok=True)


def get_analysis_result(image_id: str) -> dict[str, Any]:
    """Load a previously completed analysis by its generated image ID."""
    result_path = _result_path(image_id)
    with result_path.open("r", encoding="utf-8") as result_file:
        result: dict[str, Any] = json.load(result_file)
    return result


def list_analysis_results() -> list[dict[str, Any]]:
    """Return saved analyses, newest first, skipping unreadable result files."""
    if not RESULTS_DIR.exists():
        return []

    results: list[dict[str, Any]] = []
    for result_path in RESULTS_DIR.glob("*.json"):
        try:
            result = json.loads(result_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        if isinstance(result, dict) and result.get("success") is True:
            results.append(result)

    results.sort(
        key=lambda result: str(result.get("created_at", "")),
        reverse=True,
    )
    return results
